### PR TITLE
Login/Logout functionality added

### PR DESCRIPTION
**Pull request by karstenboettcher**
Stock login and logout functionality can be accessed by going to .../tools/login or .../tools.logout
Currently the init view creates a superuser (username: admin / password: admin). You can login by accessing the login page and using those credentials. You'll know you're logged in when you see the 'create' tool button on the index page.

I'm still going to go through and redo the site organization to better match the user/employee views of the site. That will be a big change though so I want this PR added before I send one for that.

Registration can be added if needed by adding a registration page and view. I have the code we'd need for that when the time comes.

### CODE REVIEW

**Comment by tgreen24** [comment]
I keep getting this error when trying to run anything on your branch.
`ModuleNotFoundError: No module named 'crispy_forms'`

**Comment by tgreen24** [comment]
Looks pretty good to me so far, obviously we will have to add more spots where we need to authenticate the user/ give them permissions, but I think this is a good start. Will we be able to stop people from just typing in the addresses that they could navigate to? like `/tools/create_category` for example?

**Comment by tgreen24** [comment]
You'll need to rebase before we can merge.

**Comment by karstenboettcher** [comment]
Rebased.

**Pull request merged**
