### PR TITLE
Created base.html file

### PR DESCRIPTION
**Pull request by karstenboettcher**
**Explanation of what I did and how to use it yourself:** The base.html file implements a template for the header and footer. Flexible tags can be added in the base.html file in the form of {% block tag_name %} ... {% endblock %}. These tags can then be put into any html file that {% extends 'base.html' %}. Any content between these tags will be rendered. You can set default content in the base.html file by putting content between the tags, which can be changed in your choice html file if desired.

As you can see from the changes, all html files extend base.html now. I removed the manually pasted headers and footers. All rendered content will be between the content blocks.

This is the first major refactoring I'll be doing. Please make sure each page renders its proper content still.

### CODE REVIEW

**Comment by tgreen24** [comment]
I think it needs to be something like `tools/base.html`

**Comment by karstenboettcher** [comment]
Try again, I re-specified the template directory in settings.py

**Comment by tgreen24** [comment]
The history tab takes me to the index page

**Comment by tgreen24** [comment]
Okay looks like the history page is an admin thing... disregard that

**Pull request merged**
